DROP DATABASE IF EXISTS biblioteca_pessoal_1s2026;
CREATE DATABASE biblioteca_pessoal_1s2026;
USE biblioteca_pessoal_1s2026;

CREATE TABLE editora(
	id_editora INT AUTO_INCREMENT NOT NULL,
	nome VARCHAR(255) UNIQUE NOT NULL,
    cidade VARCHAR(64),
    estado VARCHAR(64),
    pais VARCHAR(64),
    data_cadastro TIMESTAMP DEFAULT TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
);

CREATE TABLE categoria(
	id_categoria INT AUTO_INCREMENT NOT NULL,
    nome VARCHAR(128) UNIQUE NOT NULL ,
    descricao TEXT,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE autor(
	id_autor INT AUTO_INCREMENT NOT NULL,
    nome VARCHAR(255) UNIQUE NOT NULL,
    ano_nascimento YEAR,
    ano_morte YEAR,
    apresentacao TEXT,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE usuario(
	id_usuario INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	nome VARCHAR(255) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	senha VARCHAR(255) NOT NULL,
	data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	data_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE livro(
id_livro INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
id_usuario INT,
id_autor INT NOT NULL,
id_editora INT NOT NULL,
id_categoria INT NOT NULL,
titulo VARCHAR(255) NOT NULL,
sinopse TEXT NOT NULL ,
ano_publicacao YEAR NOT NULL,
lido BOOLEAN DEFAULT(0),
data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

CONSTRAINT fk_usuario_livros 
    FOREIGN KEY (id_usuario) 
    REFERENCES usuario(id_usuario)
    ON DELETE CASCADE,
    
CONSTRAINT fk_autor_livro 
    FOREIGN KEY (id_autor) 
    REFERENCES autor(id_autor)
    ON DELETE RESTRICT,

CONSTRAINT fk_categoria_livros 
    FOREIGN KEY (id_categoria) 
    REFERENCES categoria(id_categoria)
    ON DELETE RESTRICT,

CONSTRAINT fk_editora_livros 
    FOREIGN KEY (id_editora) 
    REFERENCES editora(id_editora)
    ON DELETE RESTRICT

);

