DROP DATABASE IF EXISTS biblioteca_pessoal_1s2026;
CREATE DATABASE biblioteca_pessoal_1s2026;
USE biblioteca_pessoal_1s2026;

CREATE TABLE livro(
id_livro INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
titulo VARCHAR(255) NOT NULL,
sinopse TEXT NOT NULL ,
autor VARCHAR(128) NOT NULL,
editora VARCHAR(128) NOT NULL,
categoria  VARCHAR(128) NOT NULL,
ano_publicacao YEAR NOT NULL
);

SHOW TABLES
